# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ss'
    sourceFolder: 'build.artifactStagingDirectory'
    contents: '**'
    targetFolder: 'C:\Users\heman_1dmcdfa\Desktop\SSH'
    readyTimeout: '20000'


